#!/bin/sh

clean: ../composer.json
	cd ../ && composer remove tejas/tejascaptcha && mkdir -p vendor/tejas/tejascaptcha && cd vendor
	echo Cleaned tejas/tejascaptcha - OK

update: ../composer.json
	cd ../ && composer update tejas/tejascaptcha
	echo Updated tejas/tejascaptcha - OK

test: update
	cd tejas/tejascaptcha
	echo Tested tejas/tejascaptcha - OK

install: clean
	cd ../ && composer require tejas/tejascaptcha && cd vendor/tejas/tejascaptcha
	cd ./ && ls ./
	echo Installed tejas/tejascaptcha - OK
