#!/bin/sh

clean: ../composer.json
	(shell cd ../ && composer remove tejas/tejascaptcha && mkdir -p vendor/tejas/tejascaptcha && cd vendor)
	(shell echo Cleaned tejas/tejascaptcha - OK)

update: ../composer.json
	(shell cd ../ && composer update tejas/tejascaptcha)
	(shell echo Updated tejas/tejascaptcha - OK)

test: update
	(shell cd tejas/tejascaptcha)
	(shell echo Tested tejas/tejascaptcha - OK)

install: clean
	(shell cd ../ && composer require tejas/tejascaptcha && cd vendor/tejas/tejascaptcha)
	(shell cd ./ && ls ./)
	(shell echo Installed tejas/tejascaptcha - OK)
