#!/bin/bash

clean: ../composer.json
	cd ../ && composer remove tejas/tejascaptcha && composer clearcache
	echo Cleaned tejas/tejascaptcha - OK

update: ../composer.json
	cd ../ && composer update tejas/tejascaptcha
	echo Updated tejas/tejascaptcha - OK

test: update
	cd tejas/tejascaptcha
	echo Tested tejas/tejascaptcha - OK

install: clean
	cd ../ && composer require tejas/tejascaptcha
